"""Pydantic schemas package."""

from app.schemas.artist import (
    ArtistDetailResponse,
    ArtistProfileCreate,
    ArtistProfileResponse,
    ArtistProfileUpdate,
    ArtistsListResponse,
    ArtistSummary,
    PortfolioImageCreate,
    PortfolioImageResponse,
    PortfolioImageUpdate,
    ReorderPortfolioRequest,
)
from app.schemas.booking import (
    ArtistOptionResponse,
    BookingRequestCreate,
    BookingRequestResponse,
    BookingRequestsListResponse,
    BookingRequestStatus,
    BookingRequestSummary,
    BookingRequestUpdate,
    BookingSubmissionResponse,
    ReferenceImageResponse,
    TattooSize,
)
from app.schemas.availability import (
    AvailabilityCheckRequest,
    AvailabilityCheckResponse,
    AvailabilitySlotCreate,
    AvailabilitySlotResponse,
    AvailabilitySlotUpdate,
    AvailableSlot,
    AvailableSlotsRequest,
    AvailableSlotsResponse,
    BulkAvailabilityUpdate,
    TimeOffCreate,
    TimeOffListResponse,
    TimeOffResponse,
    TimeOffUpdate,
    WeeklySchedule,
)
from app.schemas.studio import (
    BusinessHours,
    BusinessHoursDay,
    StudioCreate,
    StudioListResponse,
    StudioLogoUpload,
    StudioResponse,
    StudioUpdate,
)
from app.schemas.user import (
    AuthResponse,
    EmailVerification,
    MessageResponse,
    PasswordChange,
    PasswordReset,
    PasswordResetRequest,
    UserCreate,
    UserDetailResponse,
    UserLogin,
    UserResponse,
)

__all__ = [
    # Artist schemas
    "ArtistDetailResponse",
    "ArtistOptionResponse",
    "ArtistProfileCreate",
    "ArtistProfileResponse",
    "ArtistProfileUpdate",
    "ArtistsListResponse",
    "ArtistSummary",
    "PortfolioImageCreate",
    "PortfolioImageResponse",
    "PortfolioImageUpdate",
    "ReorderPortfolioRequest",
    # Availability schemas
    "AvailabilityCheckRequest",
    "AvailabilityCheckResponse",
    "AvailabilitySlotCreate",
    "AvailabilitySlotResponse",
    "AvailabilitySlotUpdate",
    "AvailableSlot",
    "AvailableSlotsRequest",
    "AvailableSlotsResponse",
    "BulkAvailabilityUpdate",
    "TimeOffCreate",
    "TimeOffListResponse",
    "TimeOffResponse",
    "TimeOffUpdate",
    "WeeklySchedule",
    # Booking schemas
    "BookingRequestCreate",
    "BookingRequestResponse",
    "BookingRequestsListResponse",
    "BookingRequestStatus",
    "BookingRequestSummary",
    "BookingRequestUpdate",
    "BookingSubmissionResponse",
    "ReferenceImageResponse",
    "TattooSize",
    # Studio schemas
    "BusinessHours",
    "BusinessHoursDay",
    "StudioCreate",
    "StudioListResponse",
    "StudioLogoUpload",
    "StudioResponse",
    "StudioUpdate",
    # User schemas
    "AuthResponse",
    "EmailVerification",
    "MessageResponse",
    "PasswordChange",
    "PasswordReset",
    "PasswordResetRequest",
    "UserCreate",
    "UserDetailResponse",
    "UserLogin",
    "UserResponse",
]
